### ISSUE TITLE
How to display organicArrows on mobile view ?

### ISSUE THREAD

**Issue by 007AMAN007** [rcaferati/react-awesome-slider#201]
I just started using this package today, I want to know how to display organicArrows on mobile view. I am using ```organicArrows={true}```

I know on mobile view by default arrows visibility is hidden, how I can change it's visibility ?

**Comment by trolit** [comment]
One way I can think of is adjusting slider styles within `scss` file. 

First, follow steps to configure your own `scss` file for that slider: 
https://github.com/rcaferati/react-awesome-slider/issues/147#issuecomment-706706461

Second, find that part:
```css
    @media all and (max-width: 520px) {
      visibility: hidden;
    }
```
and remove `visibility: hidden`

voilà:

<img src="https://user-images.githubusercontent.com/25982919/139276761-c6cd8bd2-d978-42bb-959c-5f1b19cf221c.png" alt="preview1" height="200"/>

**bonus:** 

You will probably want to adjust them to your needs. Just get back to part mentioned above and play with styles like how animation behaves, arrow size. Here's example on how to reduce their size. 

```css
@media all and (max-width: 520px) {
      &__arrow-left,  {
        height: 20px !important;
        margin-left: 20px;
      }

      &__arrow-right {
        height: 20px !important;
        margin-right: 20px;
      }
    }
```

result:
<img src="https://user-images.githubusercontent.com/25982919/139277493-52259ba0-7481-41b9-9e5e-9f24881a56d4.png" alt="preview2" height="200"/>
