### ISSUE TITLE
custom css

### ISSUE THREAD

**Issue by lostspirit1** [rcaferati/react-awesome-slider#67]
Olá estou tentando seguir o tutorial, gerando um css personalizado no site de demo:

```
.aws-btn {
  --slider-height-percentage: 25%;
  --slider-transition-duration: 200ms;
  --organic-arrow-thickness: 2px;
  --organic-arrow-border-radius: 0px;
  --organic-arrow-height: 22px;
  --organic-arrow-color: #00ff24;
  --control-button-width: 40%;
  --control-button-height: 25%;
  --control-button-background: transparent;
  --control-bullet-color: #a3b9d0;
  --control-bullet-active-color: #8b9db1;
  --loader-bar-color: #851515;
  --loader-bar-height: 6px;
  } 
```

meu carrousel:

```
const Slider = () =>(
    <AwesomeSlider cssModule={AwesomeSliderStyles}>
    <div data-src="http://s2.glbimg.com/4Ek8CnZSuYyyvaNQEPPiX_d-faA=/e.glbimg.com/og/ed/f/original/2017/11/24/gali1.jpg" />
    <div data-src="https://img.estadao.com.br/thumbs/640/resources/jpg/0/4/1512053836140.jpg" />
  </AwesomeSlider>   
)

export default Slider;
```

css:

```
@import './styles.scss';

.#{$root-element} {
  --scale-out-scale: 0.85;

  &--exit {
    &.#{$root-element}--moveRight,
    &.#{$root-element}--moveLeft {
      animation: scaleOut var(--slider-transition-duration) both
        var(--transition-bezier);
    }
  }
}
.aws-btn {
  --slider-height-percentage: 25%;
  --slider-transition-duration: 200ms;
  --organic-arrow-thickness: 2px;
  --organic-arrow-border-radius: 0px;
  --organic-arrow-height: 22px;
  --organic-arrow-color: #00ff24;
  --control-button-width: 40%;
  --control-button-height: 25%;
  --control-button-background: transparent;
  --control-bullet-color: #a3b9d0;
  --control-bullet-active-color: #8b9db1;
  --loader-bar-color: #851515;
  --loader-bar-height: 6px;
  } 

@keyframes scaleOut {
  to {
    transform: scale(var(--scale-out-scale));
  }
}

```

como eu deveria colocar essa customização?

**Comment by rcaferati** [comment]
Hey @lostspirit1, thanks for raising it. In this scenario, the CSS variables should go inside the root element selector. Something like:

```scss
@import './styles.scss';

.#{$root-element} {
  --slider-height-percentage: 25%;
  --slider-transition-duration: 200ms;
  --organic-arrow-thickness: 2px;
  --organic-arrow-border-radius: 0px;
  --organic-arrow-height: 22px;
  --organic-arrow-color: #00ff24;
  --control-button-width: 40%;
  --control-button-height: 25%;
  --control-button-background: transparent;
  --control-bullet-color: #a3b9d0;
  --control-bullet-active-color: #8b9db1;
  --loader-bar-color: #851515;
  --loader-bar-height: 6px;
  --scale-out-scale: 0.85;

  &--exit {
    &.#{$root-element}--moveRight,
    &.#{$root-element}--moveLeft {
      animation: scaleOut var(--slider-transition-duration) both
        var(--transition-bezier);
    }
  }
}

@keyframes scaleOut {
  to {
    transform: scale(var(--scale-out-scale));
  }
}
```
